server:
  port: 8000
  servlet: 
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      force-request: true
      force-response: true
  tomcat:
    uri-encoding: UTF-8
spring: 
 
  mvc:
    static-path-pattern: /static/**
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/heritage?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: deok%t4r3e2w1q
      
mybatis: 
  mapper-locations: 
  - /mappers/*.xml
    
    
